[package]
name = "cortex-a7"
version = "0.1.0"
edition = "2021"

[dependencies]
critical-section = { version = "1.1.1", features = ["restore-state-u32"] }
bitflags = "2.3.3"

[features]
cs-single-core = []
cs-multi-core = []
neon = []
